openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations related to contacts
  - name: Auth
    description: Auth operations
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://nodejs-hw-mongodb-024p.onrender.com
    description: Production server
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/resetPwd:
    post:
      $ref: ../swagger/paths/auth/resetPwd.yaml
  /auth/sendEmail:
    post:
      $ref: ../swagger/paths/auth/sendEmail.yaml
  /contact:
    get:
      $ref: ../swagger/paths/contact/get.yaml
    post:
      $ref: ../swagger/paths/contact/post.yaml
  /contact/{id}:
    get:
      $ref: ../swagger/paths/contact/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contact/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contact/{id}/patch.yaml
    put:
      $ref: ../swagger/paths/contact/{id}/put.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

